In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Net(nn.Module):
    def __init__(self):                # 定义网络结构 输入数据 1*32*32
        super(Net, self).__init__()

        self.conv1 = nn.Conv2d(1, 6, 3) # 输入频道 1 输出平道 6 卷积 3*3
        self.conv2 = nn.Conv2d(6, 16, 3) # 输入频道 1 输出平道 6 卷积 3*3
        self.fc1 = nn.Linear(16*28*28, 512)  # 思考why 28
        self.fc2 = nn.Linear(512, 64)  # 输入 512 输出 64
        self.fc3 = nn.Linear(64, 2)    # 输入64， 输出2

    def forward(self, x):              # 定义数据流向
        x = self.conv1(x)
        x = F.relu(x)

        x = self.conv2(x)
        x = F.relu(x)

        x = x.view(-1, 16*28*28)
        x = self.fc1(x)
        x = F.relu(x)

        x = self.fc2(x)
        x = F.relu(x)

        x = self.fc3(x)

        return x

In [3]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=12544, out_features=512, bias=True)
  (fc2): Linear(in_features=512, out_features=64, bias=True)
  (fc3): Linear(in_features=64, out_features=2, bias=True)
)


In [4]:
# 生成随机输入

input_data = torch.randn(1, 1, 32, 32)  # 1 - mini batch

print(input_data)
print(input_data.size())

tensor([[[[ 0.3495, -0.1498,  0.0304,  ...,  2.2192, -2.3294,  0.4472],
          [ 1.9358, -0.7071, -0.7085,  ..., -0.8205, -0.3066, -0.0808],
          [-0.4260, -1.9908,  1.3662,  ...,  0.3537, -0.8515,  0.8192],
          ...,
          [ 0.9590,  0.6818, -0.2893,  ...,  1.0313, -0.6791, -3.2270],
          [-2.1792, -0.5911, -0.3163,  ..., -0.7925, -1.4020, -0.8182],
          [ 0.0673,  1.2848,  0.2434,  ..., -0.0869, -0.2345, -0.4654]]]])
torch.Size([1, 1, 32, 32])


In [5]:
# 运行神经网络

out = net(input_data)
print(out)
print(out.size())

tensor([[0.0902, 0.0871]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [6]:
# 随机生成真实值
target = torch.randn(2)
target = target.view(1, -1)
print(target)

tensor([[-0.5287, -1.5738]])


In [7]:
criterion = nn.L1Loss()         # 定义损失函数
loss = criterion(out, target)   # 计算损失

print(loss)

tensor(1.1399, grad_fn=<L1LossBackward>)


In [8]:
# 反向传递

net.zero_grad() # 清零梯度

loss.backward()  # 自动计算梯度，反向传递

In [9]:
import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr=0.01)      # 权重更新规则
optimizer.step()

In [10]:
out = net(input_data)
print(out)
print(out.size())

tensor([[0.0426, 0.0389]], grad_fn=<AddmmBackward>)
torch.Size([1, 2])


In [11]:
criterion = nn.L1Loss()         # 定义损失函数
loss = criterion(out, target)   # 计算损失

print(loss)

tensor(1.0920, grad_fn=<L1LossBackward>)


In [ ]:
# 循环多次